services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=./default.yaml
      - DATABASE_URL=postgres://moxie_owner:passwd@postgres:5432/moxie?sslmode=disable
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "7654:7654"
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://127.0.0.1:7654/health
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - moxie-net

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api.localhost
    depends_on:
      api:
        condition: service_healthy
    networks:
      - moxie-net

  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy
      ui:
        condition: service_started
    networks:
      - moxie-net

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=moxie_owner
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=moxie
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U moxie_owner -d moxie"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - moxie-net

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.io"
      PGADMIN_DEFAULT_PASSWORD: "toor"
    ports:
      - "1444:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - moxie-net

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgres_data
  pgadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/pgadmin_data

networks:
  moxie-net:
