services:
  cynero:
    build: .
    ports:
      - "7654:7654"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://cynero_owner:passwd@postgres:5432/cynero?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://localhost:7654/api/health
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - cynero-net

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=cynero_owner
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_DB=cynero
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cynero_owner -d cynero"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cynero-net

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.io"
      PGADMIN_DEFAULT_PASSWORD: "toor"
    ports:
      - "1444:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - cynero-net

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgres_data
  pgadmin_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/pgadmin_data

networks:
  cynero-net:
