server:
  environment: development
  port: 7654

postgres:
  dsn: postgres://cynero_owner:passwd@postgres:5432/cynero?sslmode=require

http:
  timeout: 5s

workers:
  payment_interval: 5s
  cleaner_interval: 30m
  order_expiration: 24h
