server:
  environment: development
  port: 7654
  webhook_url: https://api.cynero.io/helius-webhook/handle

postgres:
  dsn: postgres://cynero_owner:passwd@postgres:5432/cynero?sslmode=require

http:
  timeout: 5s

workers:
  cleaner_interval: 30m
  order_expiration: 24h
