server:
  environment: development
  port: 7654
  webhook_url: https://moxie.mkfolder.dev/api/helius-webhook/handle

postgres:
  dsn: postgres://moxie_owner:passwd@postgres:5432/moxie?sslmode=require

http:
  timeout: 5s

workers:
  cleaner_interval: 30m
  order_expiration: 24h

auth:
  access_token_ttl: 15m
  refresh_token_ttl: 720h

s3:
  bucket: eu-west-1
  region: garage
  endpoint: http://localhost:3900
