server:
  environment: development
  port: 7654
  webhook_url: https://api.moxify.cc/helius-webhook/handle

postgres:
  dsn: postgres://moxie_owner:passwd@postgres:5432/moxie?sslmode=require

http:
  timeout: 5s

workers:
  cleaner_interval: 30m
  order_expiration: 24h
